server:
  port: 8096
spring:
  http:
    encoding:
      charset: utf-8
  application:
    name: springcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
